services:
  web:
    image: seproject/react:latest
    container_name: reactApp
    build: ./react-app
    command: npm start
    ports:
      - 3000:3000
  java:
    image: seproject/java:latest
    container_name: javaApi
    build: ./java-springbootApp
#    command: npm start
    ports:
      - 8080:8080